### PR TITLE
Jenkins CI: migrate to CMake

### PR DESCRIPTION
**Pull request by zheltovs**

### CODE REVIEW

**Comment by AlexVeprev** [comment]
@doyleli, could you please take a look? There are some problems with jobs trigger, do you have any idea about it?

**Review by AlexVeprev — DISMISSED** [review]
Approval to try CI

**Comment by DoyleLi** [comment]
> @DoyleLi, could you please take a look? There are some problems with jobs trigger, do you have any idea about it?

Hi @AlexVeprev , as we synced today in oneDPL meeting, we are suffering from massive infrastructure problems that currently no machine can be used for Jenkins server to run. Before the infrastructure issue been solved by IT, we cannot get these CI checks like UB20 and Windows etc.

**Comment by AlexVeprev** [comment]
@DoyleLi, thank you for confirmation! Could you also take a look at PR changes please? Do you agree with the idea? If yes, @zheltovs can proceed with updating Ubuntu and Windows configurations.

**Comment by DoyleLi** [comment]
> @DoyleLi, thank you for confirmation! Could you also take a look at PR changes please? Do you agree with the idea? If yes, @zheltovs can proceed with updating Ubuntu and Windows configurations.

Hi @AlexVeprev  The groovy file for Jenkins looks good and more clear. I think it would be OK for next step, to enable the ones for Ubuntu and Windows. But please also check the two timeout failure cases in RHEL pre-ci job to see whether we need to expand TIME_OUT value.

**Comment by DoyleLi** [comment]
LGTM, please approve and merge the PR.

**Review by ValentinaKats — APPROVED** [review]

**Pull request merged**
