### PR TITLE
Add numeric test

### PR DESCRIPTION
**Pull request by haonanya**
Signed-off-by: Haonan Yang <haonan.yang@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @AlexVeprev 
The RHEL_Check, UB1804_Check, UB20_Check failed and it seems the failures are related to CMake, could you help to have a look?
Thanks very much.

**Comment by AlexVeprev** [comment]
Hi @jinge90, your base version doesn't include renaming of sycl to dpcpp in CMakeLists, please rebase your branch on top of origin main branch and try again.

**Comment by AlexVeprev** [comment]
@haonanya now I see you have another problem in CI: error on adding adjacent_difference.pass test. Current build system has a limitation: all test files should have unique names, it allows to build/execute test one-by-one with short commands like `make adjacent_difference.pass`.

Another adjacent_difference.pass is here: https://github.com/oneapi-src/oneDPL/blob/main/test/parallel_api/numeric/numeric.ops/adjacent_difference.pass.cpp

Is it ok for you to rename the test? If not we can discuss another approach to resolve the issue.

**Comment by haonanya** [comment]
Hi, @AlexVeprev. I will add prefix "xpu_" to these std::test only, e.g. xpu_adjacent_difference.pass.cpp

**Comment by haonanya** [comment]
Hi, @AlexVeprev. These failed test should be built using "-std=c++17" options or we just do not specify std c++ version, DPC++ have already make -std=c++17 by default when no -std* option is provided.
Thanks.

**Comment by AlexVeprev** [comment]
@haonanya I see you have green checks, is your questions about `c++17` still actual?

**Comment by haonanya** [comment]
Hi, @AlexVeprev. It is my patch introduces some errors. I have redefined it. This issues has gone now.
Thanks.

**Review by jinge90 — APPROVED** [review]

**Pull request merged**
