### PR TITLE
[DOC] Add 2 new known limitations for oneDPL 2022.3 documentation

### PR DESCRIPTION
**Pull request by ValentinaKats**
Added 2 new long-term known limitations introduced in oneDPL 2022.3.
They are duplicated in oneDPL 2022.3 release notes for users notification.

### CODE REVIEW

**Review by dcbenito — CHANGES_REQUESTED** [review]
My suggestions:

* When compiling with the compiler options, ``libstdc++`` version 8 or ``libc++``, and with ``-fsycl-pstl-offload``, parallel algorithms from the std namespace called with ``oneapi::dpl::parallel_unsequenced_policy`` are offloaded to the SYCL device in accordance with the ``-fsycl-pstl-offload`` option value.
* For ``transform_exclusive_scan`` and ``exclusive_scan`` with overlapping input and destination sequences and an execution policy of ``unseq`` or ``par_unseq``, it is required that the provided input and destination iterators are equality comparable.  Furthermore, the equality comparison of the input and destination iterator must be evaluated to be true.  If these conditions are not met, the result of these algorithm calls is undefined.

**Comment by ValentinaKats** [comment]
> My suggestions:
> 
> * When compiling with the compiler options, `libstdc++` version 8 or `libc++`, and with `-fsycl-pstl-offload`, parallel algorithms from the std namespace called with `oneapi::dpl::parallel_unsequenced_policy` are offloaded to the SYCL device in accordance with the `-fsycl-pstl-offload` option value.
> * For `transform_exclusive_scan` and `exclusive_scan` with overlapping input and destination sequences and an execution policy of `unseq` or `par_unseq`, it is required that the provided input and destination iterators are equality comparable.  Furthermore, the equality comparison of the input and destination iterator must be evaluated to be true.  If these conditions are not met, the result of these algorithm calls is undefined.

@dcbenito, I changes the second note as was proposed. The first note was significantly reworded after team's discussion. Could you please review it?

**Comment by dcbenito** [comment]
My suggestion:
When compiled with the ``-fsycl-pstl-offload`` option from the Intel® oneAPI DPC++/C++ Compiler and with ``libstdc++`` version 8 or ``libc++``, ``oneapi::dpl::execution::par_unseq`` behaves similar to ``std::execution::par_unseq`` and offloading standard parallel algorithms to the SYCL device in accordance with the ``-fsycl-pstl-offload`` option value.

**Comment by ValentinaKats** [comment]
> My suggestion: When compiled with the `-fsycl-pstl-offload` option from the Intel® oneAPI DPC++/C++ Compiler and with `libstdc++` version 8 or `libc++`, `oneapi::dpl::execution::par_unseq` behaves similar to `std::execution::par_unseq` and offloading standard parallel algorithms to the SYCL device in accordance with the `-fsycl-pstl-offload` option value.

Thanks for the suggestion, Dylan. I reworked this note with a team.

**Pull request merged**
