### PR TITLE
Add CMake SYCL changes to oneDPLConfig.cmake.in

### PR DESCRIPTION
**Pull request by carbotaniuman**
This was copied over directly from CMakeLists.txt and is required for AdaptiveCPP to be recognized as a SYCL compiler. These changes were merged in #1949 so this appears to have been an oversight.

### CODE REVIEW

**Review by dmitriy-sobolev — COMMENTED** [review]
Thank you very much, @carbotaniuman. That's indeed an oversight.

Let me attach a patch to your changes: 
[dpl_config_fix.patch](https://github.com/user-attachments/files/18099011/dpl_config_fix.patch), where it is suggested:
 - Adding `CheckCXXCompilerFlag` for `check_cxx_compiler_flag`
 - Adjusting the logic with `SYCL_SUPPORT` and passing `-fsyc`l option.

Besides that, the PR looks good to me.

**Comment by mmichel11** [comment]
Thank you for this patch. With @dmitriy-sobolev's minor suggestion, this PR looks good to me as well.

**Review by dmitriy-sobolev — APPROVED** [review]
The PR looks good to me.

I've tested it by installing oneDPL, and using that installation in a micro project with `find_package(oneDPL)` in its CMakeLists.txt. I covered icx (Windows), dpcpp-cl (Windows) and acpp (Linux).

**Review by mmichel11 — APPROVED** [review]

**Comment by dmitriy-sobolev** [comment]
@carbotaniuman once again, thanks for the PR. Feel free to submit a PR updating [CREDITS.txt](https://github.com/oneapi-src/oneDPL/blob/main/CREDITS.txt) if you wish your contribution to be mentioned there.

**Pull request merged**
