### PR TITLE
Restructure test/pstl_testsuite

### PR DESCRIPTION
**Pull request by AlexVeprev**
Script to reproduce the changes based on current master:
```bash
cd test/
mv pstl_testsuite parallel_api
mv parallel_api/pstl general
mv parallel_api/std/* parallel_api/
rm -r parallel_api/std/
mv parallel_api/lambda_naming.pass.cpp parallel_api/sycl_policy.pass.cpp general/
mkdir parallel_api/iterator
mv general/iterators.pass.cpp parallel_api/transform_iterator.pass.cpp parallel_api/zip_iterator.pass.cpp parallel_api/iterator/
mv parallel_api/support .
mv parallel_api/sycl_iterator.pass.cpp general/
mv parallel_api/algorithms parallel_api/algorithm
mv parallel_api/numerics parallel_api/numeric
mv parallel_api/utilities/memory parallel_api/memory
rm -r parallel_api/utilities/
find ../jenkinsfiles -type f -exec sed -i 's/pstl_testsuite/parallel_api/g' {} \;
```

### CODE REVIEW

**Comment by AlexVeprev** [comment]
Tests from `general` are not run by CI with this PR, but PR #49 introduces many changes in test infrastructure, so I propose to update CI once #49 is ready.

**Comment by capatober** [comment]
`algorithms` -> `algorithm`
`utilities/memory` -> `memory`
`numerics` -> `numeric`

What about `experimental` folder?

**Comment by AlexVeprev** [comment]
> `algorithms` -> `algorithm`
> `utilities/memory` -> `memory`
> `numerics` -> `numeric`
> 
> What about `experimental` folder?


Renaming are done, thank you!
`experimental` does not currently exist in the target branch (master), I'd like to relocate only currently existing files, some new files/folder can be added separately.

**Comment by capatober** [comment]
Ok. I see. Just to not forget about that

**Review by capatober — APPROVED** [review]

**Pull request merged**
