### PR TITLE
add gcc workaround to all public headers

### PR DESCRIPTION
**Pull request by jinge90**
Signed-off-by: gejin <ge.jin@intel.com>

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, all.
Currently, the gcc workaround for libstdc++-9/10 is only applied to PSTL public headers, according to Alexey's comments: https://github.com/oneapi-src/oneDPL/pull/216#discussion_r635419434 the workaround should be applied to all public headers, this PR applies the workaround to tested API and random headers.

**Review by paveldyakov — APPROVED** [review]

**Comment by capatober** [comment]
I've found that `<execution>` header is missed. Could please make changes there as well?

**Comment by jinge90** [comment]
> I've found that `<execution>` header is missed. Could please make changes there as well?

I skipped it because the workaround in execution header is a little different from other ones including special handling for execution header.
Thanks very much.

**Comment by capatober** [comment]
> I skipped it because the workaround in execution header is a little different from other ones including special handling for execution header.

However, it has the same common part. It needs to be changed slightly different from other files, but still possible to use `common_config`

**Comment by jinge90** [comment]
> > I skipped it because the workaround in execution header is a little different from other ones including special handling for execution header.
> 
> However, it has the same common part. It needs to be changed slightly different from other files, but still possible to use `common_config`

Agree, we can still rely on common_config to remove the common part of the workaround code, I will update the patch.
Thanks very much.

**Review by capatober — APPROVED** [review]

**Comment by rarutyun** [comment]
What I missed in that review is tests to ensure that this workaround works and catch the situation if it's broken at some day. Other than that, looks good to me.

**Pull request merged**
