### PR TITLE
Rename the implementation directory and the main file for esimd radix sort

### PR DESCRIPTION
**Pull request by akukanov**
Two main goals:
* clearly distinguish from the oneDPL parallel backend implementation
* set the directory as the place for more "kernel templates"

Guard macros are also changed.

Alternative variants are welcome.

### CODE REVIEW

**Review by dmitriy-sobolev — APPROVED** [review]
LGTM

**Comment by dmitriy-sobolev** [comment]
Another option is to place `kt` folder inside `include/oneapi/dpl/experimental` folder so that `intel/oneapi/dpl/pstl/hetero` folder contains files for dpc++ backend only. However, I do not have strong opinion on that.

**Comment by akukanov** [comment]
> Another option is to place kt folder inside include/oneapi/dpl/experimental folder 

Actually that is my preferred option for long term, but I wanted to minimize disruptions for you at this time, and also I do not know how much the new code depends on the core oneDPL implementation. If you prefer to do it now rather than later, I will update the patch.

**Comment by dmitriy-sobolev** [comment]
> If you prefer to do it now rather than later, I will update the patch.

Let's do it now.

**Review by dmitriy-sobolev — APPROVED** [review]

**Pull request merged**
