### PR TITLE
[Doc] Update range-based API description

### PR DESCRIPTION
**Pull request by ValentinaKats**
Signed-off-by: Valentina Kats valentina.kats@intel.com

### CODE REVIEW

**Review by dcbenito — CHANGES_REQUESTED** [review]
To be consistent with other Intel Docs, for all entries (starting at line 310) please change the content in **bold**. I am using the views::iota as an example:
``views::iota``. A range factory - generates a sequence of N elements which starts from an initial value and ends by final N-1.
to:
``views::iota``**:** A range factory **that** generates a sequence of N elements which starts from an initial value and ends by final N-1.

**Comment by ValentinaKats** [comment]
> To be consistent with other Intel Docs, for all entries (starting at line 310) please change the content in **bold**. I am using the views::iota as an example:
> `views::iota`. A range factory - generates a sequence of N elements which starts from an initial value and ends by final N-1.
> to:
> `views::iota`**:** A range factory **that** generates a sequence of N elements which starts from an initial value and ends by final N-1.

@dcbenito, done. Is it ok that first A is in upper case?

**Comment by dcbenito** [comment]
@ValentinaKats yes, the capital A is fine.

**Comment by dcbenito** [comment]
Apologies for closing on accident. Thank you to @capatober for reopening.

**Review by dcbenito — APPROVED** [review]

**Pull request merged**
