### PR TITLE
Update CHANGES file with 2021.2 release changes

### PR DESCRIPTION
**Pull request by ValentinaKats**
Added 2021.2 release changes and fixed typos, broken link in previous releases changes

### CODE REVIEW

**Comment by capatober** [comment]
Is it just a copy of text from Release notes?

**Comment by dsobolev-dev** [comment]
I can see some issues that we have fixed within https://github.com/oneapi-src/oneDPL/pull/146/files, e.g. using more clear wording instead of "in debug mode".

**Comment by ValentinaKats** [comment]
> I can see some issues that we have fixed within https://github.com/oneapi-src/oneDPL/pull/146/files, e.g. using more clear wording instead of "in debug mode".

@dsobolev-dev, thanks for noticing. Added missed changes.

**Comment by ValentinaKats** [comment]
> Is it just a copy of text from Release notes?

Yes, it is. + added missed space in one line.

**Review by capatober — APPROVED** [review]

**Pull request merged**
