### PR TITLE
Remove assertions in minmax_element binary operator

### PR DESCRIPTION
**Pull request by julianmi**
The current `minmax_element` implementation requires in-order processing since its binary operator assumes that the index of the first input is lower than that of the second input. This is a performance improvement since we can skip the case when both input values are equal. The in-order processing is guaranteed by following the non-commutative reduce pattern. We currently check the index order with assertions with lead to high overheads when compiled without `NDEBUG`. This may lead to test timeouts or user code looking to be hanging. I think the assertions are not needed since we enforce them in the in-order reduce pattern and we don't use them in the similar `min_element` algorithm.

### CODE REVIEW

**Comment by dmitriy-sobolev** [comment]
@julianmi, could you remove the assertions in `include\oneapi\dpl\pstl\hetero\algorithm_ranges_impl_hetero.h`?

Meanwhile, I found no mention if assert can be used in SYCL code. 
Given that there is a corresponding extension in [oneAPI DPC++ Compiler](https://github.com/intel/llvm/blob/5d02eaedcba58d1139dd69a88e8e372bf582bbda/sycl/doc/extensions/supported/sycl_ext_oneapi_assert.asciidoc), I assume that we should avoid using asserts in kernels, or at least use them conditionally.

**Comment by julianmi** [comment]
> @julianmi, could you remove the assertions in `include\oneapi\dpl\pstl\hetero\algorithm_ranges_impl_hetero.h`?


Done.

> Meanwhile, I found no mention if assert can be used in SYCL device code reading its specification. Given that there is a corresponding extension in [oneAPI DPC++ Compiler](https://github.com/intel/llvm/blob/5d02eaedcba58d1139dd69a88e8e372bf582bbda/sycl/doc/extensions/supported/sycl_ext_oneapi_assert.asciidoc), I assume that we should avoid using asserts in kernels, or at least use them conditionally.

I agree with your statement. I looks like assert seems to work for now in kernel code though. Anyways, I think our tests should capture such semantic issue in our kernels (and they do for this specific case).

**Review by dmitriy-sobolev — APPROVED** [review]
LGTM

**Review by danhoeflinger — APPROVED** [review]
LGTM

**Pull request merged**
