### PR TITLE
Fix queue creation for reduce_by_segment.pass

### PR DESCRIPTION
**Pull request by danhoeflinger**
Adding `TestUtils::get_test_queue()` for queue creation.

### CODE REVIEW

**Review by dmitriy-sobolev — APPROVED** [review]

**Comment by danhoeflinger** [comment]
Very simple PR, but I'm still going to wait for CI to run this before merging.

**Review by SergeyKopienko — APPROVED** [review]
LGTM

**Comment by dmitriy-sobolev** [comment]
> Very simple PR, but I'm still going to wait for CI to run this before merging.

Note, that the CI runs only `sycl_iterator` tests with DPC++ policies. It is better to verify the fix locally.

**Comment by danhoeflinger** [comment]
> > Very simple PR, but I'm still going to wait for CI to run this before merging.
> 
> Note, that the CI runs only `sycl_iterator` tests with DPC++ policies. It is better to verify the fix locally.

Yes, I did that as well.  Will merge shortly.

**Pull request merged**
