### PR TITLE
Move merge/merge-sort device patterns into separate files

### PR DESCRIPTION
**Pull request by dmitriy-sobolev**
This PR moves merge and merge-sort patterns into separate files similarly to `parallel_backend_sycl_reduce.h`. Additionally. it replaces `::std` with `std` according to the earlier agreed coding guideline.

This is a preparation step for adding a single-work-group implementation for merge-sort, which may inflate already large 
`parallel_backend_sycl.h` file.

### CODE REVIEW

**Comment by mmichel11** [comment]
From a visual review, the changes LGTM. Did you try manually running a `merge` / `sort` DPCPP backend test as a sanity check since the GH CI only runs the sycl iterator tests?

**Comment by dmitriy-sobolev** [comment]
> From a visual review, the changes LGTM. Did you try manually running a `merge` / `sort` DPCPP backend test as a sanity check since the GH CI only runs the sycl iterator tests?

Yes. I've done it: the tests pass.

**Review by julianmi — DISMISSED** [review]
LGTM

**Review by mmichel11 — DISMISSED** [review]
LGTM

**Comment by dmitriy-sobolev** [comment]
I've also applied clang-format. @mmichel11 and @julianmi, could you reapprove the PR?

**Review by mmichel11 — APPROVED** [review]
Reapproving after clang-format

**Pull request merged**
