### PR TITLE
CI: update Ubuntu 18.04 conf and fix Windows conf

### PR DESCRIPTION
**Pull request by AlexVeprev**
In order to support newer compiler in CI we have to apply some alignments into CI.

### CODE REVIEW

**Comment by AlexVeprev** [comment]
@DoyleLi, please take a look

**Comment by AlexVeprev** [comment]
@capatober, check on Ubuntu 18.04 becomes very similar to existing check on Ubuntu 20.04 (https://github.com/oneapi-src/oneDPL/blob/main/jenkinsfiles/UB20_Check.groovy#L237). There is still difference in libstdc++ versions, but please let me know if you'd like to differentiate the configurations with some additional parameters.

**Comment by capatober** [comment]
Does it make sense to add icpx/icpc compiler instead for Ubuntu18?

**Comment by AlexVeprev** [comment]
You mean to change to TBB backend? `icpc` doesn't support `dpcpp` backend, but with `icpx` it is possible, yes.

**Comment by capatober** [comment]
I meant changing to TBB backend. I think it's enough to cover `dpcpp` backend with Ubuntu20 and RHEL for in pre-CI testing

**Comment by AlexVeprev** [comment]
> I meant changing to TBB backend. I think it's enough to cover `dpcpp` backend with Ubuntu20 and RHEL for pre-CI testing

Applied, works on my machine.

**Comment by DoyleLi** [comment]
LGTM. Thanks.

**Review by capatober — APPROVED** [review]

**Pull request merged**
