### PR TITLE
[CI] add FPGA emulator testing

### PR DESCRIPTION
**Pull request by dmitriy-sobolev**
Let's test FPGA backend in the CI to detect any related issues early.

### CODE REVIEW

**Review by SergeyKopienko — APPROVED** [review]
LGTM

**Comment by dmitriy-sobolev** [comment]
I will return to that PR after #853 is merged.

**Review by julianmi — APPROVED** [review]
LGTM

**Review by SergeyKopienko — APPROVED** [review]
LGTM

**Pull request merged**
