### PR TITLE
Fix header path in pkg-config files generated without OS subdir

### PR DESCRIPTION
**Pull request by dmitriy-sobolev**
This generates the right header path for the package config files when they are generated with `SKIP_HEADERS_SUBDIR` set to `TRUE`.
This is useful for creation of e.g., conda packages which do not have `windows` or `linux` subdirectories.

### CODE REVIEW

**Comment by adamfidel** [comment]
Could you please update `cmake/README.md` and add the option for `SKIP_HEADERS_SUBDIR` to the documentation here?
https://github.com/oneapi-src/oneDPL/blob/06f7b0a50768e573a9e9ae8ba3be7160dd84696e/cmake/README.md?plain=1#L111


I did some testing and I can confirm that running `cmake -DOUTPUT_DIR=/tmp/install -DSKIP_HEADERS_SUBDIR=true -P cmake/scripts/generate_config.cmake` does modify the pkg-config files as expected. So I believe these changes work as expected.

Strangely, I cannot run the CMake install target as a whole. I get the following error:
```
$ cmake --install . --prefix /tmp/install
CMake Error: Error processing file: [...snip...]/cmake/cmake_install.cmake
```
I get this same error on main however, so it might be something weird with my setup. It is not something related to your changes.

**Comment by adamfidel** [comment]
I'm not familiar with how the installed package is intended to be used with respect to pkg-config, but does it make sense to create a single `pkgconfig/dpl.pc` file if `SKIP_HEADERS_SUBDIR` is set to true? With these changes, it will create both `pkgconfig-lin/dpl.pc` and `pkgconfig-win/dpl.pc` which have identical contents.

It might be okay, but I'm just wondering if it would be cleaner to create a single pkg-config file instead of two identical ones here.

**Review by adamfidel — APPROVED** [review]
LGTM.

**Comment by dmitriy-sobolev** [comment]
> Could you please update `cmake/README.md` and add the option for `SKIP_HEADERS_SUBDIR` to the documentation here?
> 
> https://github.com/oneapi-src/oneDPL/blob/06f7b0a50768e573a9e9ae8ba3be7160dd84696e/cmake/README.md?plain=1#L111
> 
> I did some testing and I can confirm that running `cmake -DOUTPUT_DIR=/tmp/install -DSKIP_HEADERS_SUBDIR=true -P cmake/scripts/generate_config.cmake` does modify the pkg-config files as expected. So I believe these changes work as expected.
> 
> Strangely, I cannot run the CMake install target as a whole. I get the following error:
> 
> ```
> $ cmake --install . --prefix /tmp/install
> CMake Error: Error processing file: [...snip...]/cmake/cmake_install.cmake
> ```
> 
> I get this same error on main however, so it might be something weird with my setup. It is not something related to your changes.

Thank you for the review. I updated the cmake documentation. 

It seems cmake files should be generated before using `cmake --install` command according to a note from note from https://cmake.org/cmake/help/latest/manual/cmake.1.html#install-a-project:
> CMake provides a command-line signature to install an already-generated project binary tree:

You can try these commands:
```
cmake --configure ..
cmake --install . --prefix /path/to/dpl
```

**Comment by dmitriy-sobolev** [comment]
> I'm not familiar with how the installed package is intended to be used with respect to pkg-config, but does it make sense to create a single `pkgconfig/dpl.pc` file if `SKIP_HEADERS_SUBDIR` is set to true? With these changes, it will create both `pkgconfig-lin/dpl.pc` and `pkgconfig-win/dpl.pc` which have identical contents.
> 
> It might be okay, but I'm just wondering if it would be cleaner to create a single pkg-config file instead of two identical ones here.

It definitely makes sense. I've done that. 

I expect the following use case of the pkg-config files. A user sources oneDPL, the source script sets path `PKG_CONFIG_PATH`, what allows compiling a third-party apps as:
```
# `pkg-config --cflags dpl` is evaluated to -I/path/to/oneDPL/include
icpx -fsycl my_app.cpp `pkg-config --cflags dpl` 
```

**Review by adamfidel — APPROVED** [review]
Great, thanks for making those changes!

**Pull request merged**
